apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: musicstore
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: musicstore
    spec:
      containers:
      - name: musicstore
        image: marcelv/mvcmusicstore:__Build.BuildId__
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 1G
            cpu: 2
          limits:
            memory: 1G
            cpu: 2
      nodeSelector:
            kubernetes.io/role: agent
            beta.kubernetes.io/os: windows
            type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
      - key: azure.com/aci
        effect: NoSchedule
      imagePullSecrets:
        - name: pullkey